name: CI

defaults:
  run:
    working-directory: ./
    
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 2 * * 0'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        cache: 'pip'
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        cache: 'pip'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Build
